import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-blog',
  templateUrl: './blog.component.html',
  styleUrls: ['./blog.component.css']
})
export class BlogComponent implements OnInit {

  slug = "";
  hasPost = false;
  post = [];

  posts = {
    "track-your-progress-inventory-software" : [{
      featured_image: '/assets/blog/image-3.jpg',
      slug: "A POS system or Point of Sale system refers to the cashier counters at a shop or retail store that carries out checkout procedures and prepares invoices. The POS system is made up of several hardware and software that facilitate the billing process. Typically a POS system enables you to...",
      title: 'Track Your Progress with Inventory Software',
      content: "<p>A POS system or Point of Sale system refers to the cashier counters at a shop or retail store that carries out checkout procedures and prepares invoices. The POS system is made up of several hardware and software that facilitate the billing process. Typically a POS system enables you to:</p>" +
      "<ul>" +
      "<li>Analyze data and adjust purchasing and sales for the concerning items accordingly.</li>" +
      "<li>Study the history for sales to buy particular items according to the seasonal trends.</li>" +
      "<li>Bill accurate prices of items to save the possible errors those surfaces due to unnecessarily rounding off prices of items.</li>" + 
      "</ul>" + 
      "<p>Inventory Management Software</p>" + 
      "<p>With the introduction of inventory software programs in the retail stores, the POS software have advanced to provide efficient and more accurate sales data that helps to increase the profit margins of the retail business. Inventory software helps you track usage of items, monitoring the changes in dollar costsFree Reprint Articles, and easy editions in the items that are being purchased.</p>"+
      "<p>Integrating Inventory within POS</p>" +
      "<p>The inventory can be handled and monitored at the cash counter itself by incorporating them with POS systems. The benefit of incorporating these together helps in maintaining the records of each sale and keeps them up-to-date. The inventory helps you analyze the sales and the related profits that are earned. One gets all the information regarding the merchandising and purchasing items that are sold the most. Manual editions and billing may not have provided the retailers with information that would have helped them in increasing their profit margins.</p>" +
      "<p>Features of Inventory Software</p>" +
      "<p>The inventory management software helps the retailer control of their checkout system. Here are a few pointers as to why one must install inventory software at their retail stores.</p>" +
      "<ul>" +
      "<li>The software helps retailer to analyze their sales and stores information related to the retail store and processes them efficiently.</li>" +
      "<li>The inventory helps you make critical decisions by generating powerful reports that involve detailed sale analysis.</li>" +
      "<li>The software helps in keeping the business in competition with other existing businesses by keeping inventory records and information regarding orders and purchases.</li>" +
      "<li>Lets the retailers manage inventory for several locations.</li>" +
      "<li>Several inventory software help in creating reorders within few minutes and maintains purchase orders for future references.</li>" +
      "</ul>" +
      "<p>Incorporating inventory software with point of sale systems helps in seamless functioning of the checkout systems at retail stores. Keeping accurate sales records and powerful reports that are generated by the inventory management software help in making critical decisions.</p>"
    }],
 
    "pos-inventory-management-saves-time-money-reduces-shrink" : [{ 
      featured_image: '/assets/blog/image-1.jpg',
      slug: "Retail is a demanding field of service for customers with specific wants and needs. Not meeting those customers’ needs will find them drifting off to competitors. One wants to ensure their shelves and counters are not barren from the stock they should have in place. A retail point of sale...",
      title: 'POS Inventory Management Saves Time, Money, and Reduces Shrink',
      content: "<p>Retail is a demanding field of service for customers with specific wants and needs. Not meeting those customers’ needs will find them drifting off to competitors. One wants to ensure their shelves and counters are not barren from the stock they should have in place. A retail point of sale inventory management system can greatly assist with this. In addition, it can leave your employees available for servicing customers and keeping their work areas clean.</p>" +
        "<p>The basic idea behind point of sale inventory management is for replenishment to occur based off of sales. Different systems operate in different ways depending on how it is set up. Most systems will offer the same basic benefits to the retailer and that is what we will look at.</p>" +
        "<p>Reducing Shrink</p>" +
        "<p>A high source of shrinkage in retail comes with the loss or misplacement of paperwork. The size of the company will affect how drastically it affects them, thus the range is wide. It can easily range into thousands or millions of dollars for larger companies. Smaller companies will want to be reducing shrinkage just to help shave money off of expenses. A point of sale inventory management system helps to greatly reduce the human interaction factor with the ordering process. This results in less lost paperwork, over ordering, or botched ordering.</p>" +
        "<p>Higher Accuracy in Inventory</p>" +
        "<p>A point of sale inventory management system takes the guesswork out of ordering and providing stock. The inventory of the store is stored away into a database with all pertinent information tied to it. This includes things like case count size, UPC, SKU, price per unit, and various other bits of information. When a customer purchases an item, the quantity is adjusted in the database. This enables one to use the company computer system to input a UPC number and receive an accurate idea of the number of an item one has left. One may also find it worthwhile to invest in hand-held computer systems which allows scanning of bar codes and shelf tags on the floor to display inventory and order information. This is particularly beneficial in large stores as it saves several back and forth trips.</p>" +
        "<p>Point of Sale Ordering</p>" +
        "<p>This is a great benefit of a point of sale inventory management system. One can automate a majority of their ordering practices which helps to eliminate human error and keep replenishment at optimum efficiency. The method in which it occurs will be dependant on the system. When a customer purchases an item, the system speaks to the inventory management system to let it know it is now down an object. With some systems, it would automatically place an order with a distributor to replace that item. For other products it may operate by the case. One would not particularly want cases of canned cat food being ordered every time one can sells after all. A business owner can automate a majority of their ordering in this way while still retaining some control for themselves and management through the computer systems. Manual orders are perfectly possible and will still occasionally be necessary for promotions or customer needs.</p>" +
        "<p>These are a few of the main benefits that a point of sale inventory management system can offer to a business owner. Automating the order and inventory process saves you and your employees a lot of time and paperwork. This frees employees up to do more important things such as offering superior customer service to help clear those well-stocked shelves. This in turnBusiness Management Articles, means higher profit and reduced shrink.</p>" +
        ""
    }],

    "why-your-business-needs-inventory-management-software-retail-point-of-sale-software In order to overcome this difficulty inventory management, and in consequence the inventory management software..." : [
      {
        featured_image: '/assets/blog/image-2.jpg',
        slug: "In order to overcome this difficulty inventory management, and in consequence the inventory management software, was introduced. Inventory management deals with specifying the shape and percentage of stocked goods and with the overseeing and controlling of the ordering, storage and use of the goods. It also helps in demand-forecasting. Let...",
        title: "Why Your Business Needs an Inventory Management Software and Retail Point of Sale Software?",
        content: "<p>In order to overcome this difficulty inventory management, and in consequence the inventory management software, was introduced. Inventory management deals with specifying the shape and percentage of stocked goods and with the overseeing and controlling of the ordering, storage and use of the goods. It also helps in demand-forecasting. Let us look at some of the advantages of implementing inventory management software:</p>"+
        "<ol>" +
          "<li>It provides support for OEM/EN barcodes.</li>" +
          "<li>Displays images of the goods.</li>" +
          "<li>It provides a mass-update of item masters.</li>" +
          "<li>It provides product details with multiple categories like brand, size, design, colour, etc.</li>" +
          "<li>It can maintain multiple units, sites and stock points.</li>" +
          "<li>The inventory can be valued in just one click.</li>" +
          "<li>Helps in effective task management. It includes Tax Master with Tax Jurisdiction, VAT/CST auto calculation, and Tax slab mapping for pricing based VAT calculation.</li>" +
          "<li>It has a strong assortment concept for the setting up of promotions and other actions.</li>" +
          "<li>Also has assortments and article based inventory planning.</li>" +
          "<li>Helps in effective tracking of good via goods-in-transit reporting.</li>" +
        "</ol></br>" +
        "<p>An inventory management software and a retail point of sales software together make things at the point of sale much easier and technologically organized. This system is usually implemented at the cash counter. Let us now look at a few advantages of the retail point of sale system:</p>" +
        "<ol>" +
          "<li>It is efficient while collecting tender information like redeeming loyalty points, gift vouchers, etc.</li>" +
          "<li>It can directly scan barcodes.</li>" +
          "<li>It can use the OEM code instead of creating a new code in case the item was purchased with the OEM code.</li>" +
          "<li>It can block sales if the inventory is zero.vv</li>" +
          "<li>It can check the stock of a product at other stores online.</li>" +
          "<li>In case a customer has never shopped there before, their details can be downloaded online.</li>" +
          "<li>Helps greatly in data synchronization. It automatically performs updating of the sale and stock back to the retail head office.</li>" +
          "<li>It is very secure. It does auto backup.</li>" +
          "<li>The retail point of sale systemallows customers to shop in different departments and then collect the items at the cash counter using a delivery slip.</li>" +
          "<li>If a store is a franchisee store, the POS helps in controlling stocks without affecting the accounts. The promotions, pricing, security, etc., can be centrally controlled.</li>" +
        "</ol></br>" +
        "<p>Technology and automation have helped businesses grow and improved processes. These two systems have improved retailing in a big wayPsychology Articles, encouraging and taking care of more customers than ever before!</p>"
      }
    ]
  };

  

  constructor(private route: ActivatedRoute) { }

  ngOnInit() {

    this.route.paramMap.subscribe(params => {
      this.slug = params.get('slug');
    });

    if (this.slug) {

      if (this.posts[this.slug]) {

        this.hasPost = true;
      }
    }
  }
   
   
}
